spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employee_management
    username: chamath
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: employee_management
      database-platform: org.hibernate.dialect.PostgreSQLDialect
